apiVersion: v1
kind: Secret
metadata:
  name: finops-secrets
  namespace: finops
type: Opaque
stringData:
  OPENAI_API_KEY: "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"
