apiVersion: v1
kind: Service
metadata:
  name: finops-dashboard
  namespace: finops
  labels:
    app: finops-dashboard
spec:
  type: LoadBalancer
  selector:
    app: finops-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 8501
      protocol: TCP
